# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='Start')),
                ('end', models.TimeField(verbose_name='End')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.PositiveIntegerField(verbose_name='Cabinet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Subject', verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Teacher', verbose_name='Teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.RingsSchedule', verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, verbose_name='Week day')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='department.Group', verbose_name='Group')),
                ('subjects_schedule', models.ManyToManyField(to='schedule.SubjectSchedule', verbose_name='subjects schedule')),
            ],
        ),
    ]
