# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='group',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subjects_schedule',
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='department.Group', verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='week_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default=1, max_length=1, verbose_name='Week day'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
